import type { RuleDefinition } from "@/domain/rules/types";
import {
  answerExcludesAll,
  answerGreaterThan,
  answerIn,
  answerIncludesAny,
  factTrue,
} from "@/domain/rules/helpers";

/**
 * All 42 rules from `rule_catalog.csv`, hand-translated into typed
 * predicates per spec §11's "translate CSV rules into typed code" — see
 * OPEN_QUESTIONS.md item 21 for why (the condition column is not a
 * strict re-parseable DSL) and for the automation-level policy (a rule
 * is only ever auto-matched when its full condition is decidable; a
 * `Manual`-tagged rule, or one with an undecidable clause, always
 * returns `false` and is flagged `requiresManualReview`, never silently
 * resolved). `validateCatalog.ts` checks every field below against
 * `rule_catalog.json` at test/startup time — Rule ID, severity, and
 * critical-override are never allowed to drift from the CSV.
 *
 * Every `answerIn`/`answerIncludesAny` option list quotes
 * `questionnaire.csv`'s real option strings, not the CSV condition
 * column's own abbreviations of them (e.g. `R-TIME-002`'s condition text
 * says "כלולות בשכר", the real TIME-07 option is "כלולות בשכר החודשי")
 * — each abbreviation was resolved against the actual option list before
 * being encoded here, never guessed.
 */
export const RULE_CATALOG: readonly RuleDefinition[] = [
  // ---------------------------------------------------------------
  // דיני עבודה — EMP
  // ---------------------------------------------------------------
  {
    ruleId: "R-EMP-001",
    domainArea: "דיני עבודה",
    topic: "היעדר מסמך תנאי עבודה",
    inputs: ["EMP-01", "EMP-02"],
    conditionRaw: "EMP-01=לא AND EMP-02=לא",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "להסדיר מסמכי תנאי עבודה ולבדוק רטרואקטיבית את האוכלוסייה.",
    possibleService: "הסכמי עבודה/הודעות לעובד",
    legalSourceUrl:
      "https://www.gov.il/BlobFolder/generalpage/work-rights-working-conditions-notification/he/workers-rights_admission-to-work_work-rights-working-conditions-notification_Hodaa-Pirot.pdf",
    cautionNote: "יש לבדוק חריגים ומועד מסירה לפי נסיבות.",
    evaluate: (facts) => answerIn(facts, "EMP-01", ["לא"]) && answerIn(facts, "EMP-02", ["לא"]),
  },
  {
    ruleId: "R-EMP-002",
    domainArea: "דיני עבודה",
    topic: "אין הודעה אך קיים הסכם",
    inputs: ["EMP-01", "EMP-02", "DOC-01"],
    conditionRaw: "EMP-02=לא AND EMP-01=כן/חלק",
    automationLevel: "AI+Rule",
    baseSeverity: 2,
    criticalOverride: false,
    recommendation: "AI יבדוק אם ההסכם כולל את פרטי החובה; אין לקבוע הפרה אוטומטית.",
    possibleService: "בדיקת/עדכון הסכמים",
    legalSourceUrl: "https://fs.knesset.gov.il/%5C18%5Claw%5C18_lsr_301205.pdf",
    cautionNote: "סעיף 2(ד): הסכם מתאים עשוי למלא את החובה.",
    evaluate: (facts) =>
      answerIn(facts, "EMP-02", ["לא"]) && answerIn(facts, "EMP-01", ["כן, עם כולם", "רק עם חלקם"]),
  },
  {
    ruleId: "R-EMP-003",
    domainArea: "דיני עבודה",
    topic: "שינוי תנאים ללא תיעוד",
    inputs: ["EMP-04", "EMP-05"],
    conditionRaw: "EMP-04=כן AND EMP-05=לפעמים/לא",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "למפות שינויים וליצור מנגנון הודעה ותיעוד.",
    possibleService: "נוהל שינוי תנאי העסקה",
    legalSourceUrl:
      "https://www.gov.il/BlobFolder/generalpage/work-rights-working-conditions-notification/he/workers-rights_admission-to-work_work-rights-working-conditions-notification_Hodaa-Pirot.pdf",
    cautionNote: "נדרשת בדיקה לפי סוג השינוי והחריגים.",
    evaluate: (facts) => answerIn(facts, "EMP-04", ["כן"]) && answerIn(facts, "EMP-05", ["לפעמים", "לא"]),
  },

  // ---------------------------------------------------------------
  // שעות עבודה — TIME
  // ---------------------------------------------------------------
  {
    ruleId: "R-TIME-001",
    domainArea: "שעות עבודה",
    topic: "עובדים שאינם מדווחים שעות",
    inputs: ["TIME-01", "TIME-03", "GEN-09"],
    conditionRaw: "TIME-01=רק חלק/רק שעתיים/לא",
    automationLevel: "Rule+Manual",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לבחון תחולת חוק שעות עבודה ומנוחה והאם ההחרגה מוצדקת.",
    possibleService: "בדיקת נוכחות ומשרות אמון",
    legalSourceUrl: null,
    cautionNote: "אין להסיק שמשרת אמון רק כי כך הוגדרה.",
    evaluate: (facts) =>
      answerIn(facts, "TIME-01", ["רק חלק מהעובדים", "רק עובדים שעתיים", "לא"]),
  },
  {
    ruleId: "R-TIME-002",
    domainArea: "שעות עבודה",
    topic: "שעות נוספות כלולות בשכר/לא משולמות",
    inputs: ["TIME-06", "TIME-07", "DOC-01", "DOC-03", "DOC-04"],
    conditionRaw: "TIME-06=כן/לעיתים AND TIME-07 כולל כלולות בשכר או לא משולמות",
    automationLevel: "AI+Rule",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "בדיקה מיידית של מנגנון התשלום והפרשי שכר אפשריים.",
    possibleService: "בדיקת שעות נוספות",
    legalSourceUrl: null,
    cautionNote: "Override קריטי כאשר הפרקטיקה רוחבית/ממושכת; יש לבדוק חריגים.",
    evaluate: (facts) =>
      answerIn(facts, "TIME-06", ["כן, באופן קבוע", "כן, לעיתים"]) &&
      answerIncludesAny(facts, "TIME-07", ["כלולות בשכר החודשי", "לא משולמות בנפרד"]),
  },
  {
    ruleId: "R-TIME-003",
    domainArea: "שעות עבודה",
    topic: "רכיב גלובלי שאינו נפרד/לא מגובה",
    inputs: [
      "TIME-07",
      "TIME-08",
      "DOC-01",
      "DOC-03",
      "DOC-04",
      "cross_check.time.global_overtime_attendance_mismatch",
    ],
    conditionRaw: "TIME-07 כולל גלובלי AND (TIME-08=לא OR מסמך/נוכחות אינם תומכים)",
    automationLevel: "AI+Rule",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לבדוק סבירות הרכיב, הפרדה ותאימות לביצוע בפועל.",
    possibleService: "בדיקת הסכמי שכר",
    legalSourceUrl: null,
    cautionNote: "הניקוד יושפע מחוסר התאמה בין רכיב גלובלי לשעות בפועל.",
    // Second OR clause is decidable once the cross-check engine (task
    // #47) produces `cross_check.time.global_overtime_attendance_mismatch`
    // (attendance/document don't support the assumed global hours).
    evaluate: (facts) =>
      answerIncludesAny(facts, "TIME-07", ["רכיב שעות נוספות גלובלי"]) &&
      (answerIn(facts, "TIME-08", ["לא"]) ||
        factTrue(facts, "cross_check.time.global_overtime_attendance_mismatch")),
  },
  {
    ruleId: "R-TIME-004",
    domainArea: "שעות עבודה",
    topic: "עבודה בלילה",
    inputs: ["TIME-13"],
    conditionRaw: "TIME-13=כן",
    automationLevel: "Rule+Manual",
    baseSeverity: 2,
    criticalOverride: false,
    recommendation: "לבדוק מגבלות עבודת לילה, שעות נוספות והסדרים מיוחדים.",
    possibleService: "בדיקת משמרות",
    legalSourceUrl: null,
    cautionNote: "עצם עבודת הלילה אינה הפרה.",
    evaluate: (facts) => answerIn(facts, "TIME-13", ["כן"]),
  },
  {
    ruleId: "R-TIME-005",
    domainArea: "שעות עבודה",
    topic: "עבודה במנוחה שבועית/חג",
    inputs: ["TIME-14"],
    conditionRaw: "TIME-14=כן/לעיתים",
    automationLevel: "Rule+Manual",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לבדוק היתר/חריג, גמול ומנוחה חלופית.",
    possibleService: "בדיקת העסקה בשבת/חג",
    legalSourceUrl: "https://www.gov.il/he/service/request-for-employment-during-weekend-or-extra-hours",
    cautionNote: "עצם העבודה אינה בהכרח הפרה.",
    evaluate: (facts) => answerIn(facts, "TIME-14", ["כן, באופן קבוע", "לעיתים"]),
  },
  {
    ruleId: "R-TIME-006",
    domainArea: "שעות עבודה",
    topic: "הפסקה שבה העובד נשאר זמין",
    inputs: ["TIME-15"],
    conditionRaw: "TIME-15=כן/תלוי",
    automationLevel: "Rule+Manual",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לבחון האם זמן ההפסקה מהווה זמן עבודה לצורך תשלום.",
    possibleService: "בדיקת זמני עבודה",
    legalSourceUrl: null,
    cautionNote: "תלוי בחובת הנוכחות וביכולת העובד לצאת.",
    evaluate: (facts) => answerIn(facts, "TIME-15", ["כן", "תלוי בתפקיד"]),
  },
  {
    ruleId: "R-TIME-007",
    domainArea: "שעות עבודה",
    topic: "עבודה מחוץ לשעות ללא מנגנון דיווח",
    inputs: ["TIME-16", "TIME-01"],
    conditionRaw: "TIME-16=כן/לעיתים AND אין מנגנון מתאים",
    automationLevel: "Rule+Manual",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "להסדיר זמינות, דיווח ועבודה מרחוק.",
    possibleService: "מדיניות עבודה מרחוק",
    legalSourceUrl: null,
    cautionNote: "דורש בירור עובדתי; לא כל הודעה ב-WhatsApp היא זמן עבודה.",
    // "אין מנגנון מתאים" ("no appropriate mechanism") names no field
    // anywhere in questionnaire.csv or a defined fact — genuinely
    // undecidable, never auto-matched (OPEN_QUESTIONS.md item 21).
    alwaysRequiresManualReview: true,
    evaluate: () => false,
  },

  // ---------------------------------------------------------------
  // זכויות סוציאליות — SOC
  // ---------------------------------------------------------------
  {
    ruleId: "R-SOC-001",
    domainArea: "זכויות סוציאליות",
    topic: "הפרשות פנסיה חסרות/מעוכבות",
    inputs: ["SOC-01"],
    conditionRaw: "SOC-01=יש חריגים/לא",
    automationLevel: "Rule+Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "בדיקת חוסרים והשלמת הפקדות בהקדם.",
    possibleService: "בדיקת פנסיה",
    legalSourceUrl: null,
    cautionNote: "נדרש אימות מול חשבת השכר והסדרים החלים.",
    evaluate: (facts) => answerIn(facts, "SOC-01", ["יש חריגים/עיכובים", "לא"]),
  },
  {
    ruleId: "R-SOC-002",
    domainArea: "זכויות סוציאליות",
    topic: "אי-בדיקת קופה פעילה",
    inputs: ["SOC-02"],
    conditionRaw: "SOC-02=לפעמים/לא",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "להסדיר שאלון קליטה ומנגנון מעקב.",
    possibleService: "נוהל פנסיה לקליטה",
    legalSourceUrl: null,
    cautionNote: "יש לבחון לפי צו ההרחבה והנסיבות.",
    evaluate: (facts) => answerIn(facts, "SOC-02", ["לפעמים", "לא"]),
  },
  {
    ruleId: "R-SOC-003",
    domainArea: "זכויות סוציאליות",
    topic: "סעיף 14 אינו מאומת",
    inputs: ["SOC-04", "SOC-05", "DOC-01"],
    conditionRaw: "SOC-05=כן/חלק/לא יודעת",
    automationLevel: "AI+Rule",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לאמת את ההסדרה, מועד תחולתה ושיעורי ההפקדה.",
    possibleService: "בדיקת סעיף 14",
    legalSourceUrl:
      "https://www.gov.il/BlobFolder/servicequestionnaire/approval-agreement-section28-request/he/guidelines-applying-retroactively-section14.pdf",
    cautionNote: "אין להסיק תחולה רק מאזכור 'סעיף 14' בחוזה.",
    evaluate: (facts) => answerIn(facts, "SOC-05", ["כן", "בחלק מההסכמים", "לא יודעת"]),
  },

  // ---------------------------------------------------------------
  // שכר ותגמול — PAY
  // ---------------------------------------------------------------
  {
    ruleId: "R-PAY-001",
    domainArea: "שכר ותגמול",
    topic: "בונוס/עמלה ללא הסדרה כתובה",
    inputs: ["PAY-01", "PAY-04"],
    conditionRaw: "PAY-01=כן AND PAY-04=לא/חלקית",
    automationLevel: "Rule+Manual",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לתעד מנגנון זכאות, חישוב וסיום.",
    possibleService: "תכנית עמלות/בונוסים",
    legalSourceUrl: null,
    cautionNote: "המשמעות לזכויות סוציאליות תלויה במהות התשלום.",
    evaluate: (facts) => answerIn(facts, "PAY-01", ["כן"]) && answerIn(facts, "PAY-04", ["לא", "חלקית"]),
  },
  {
    ruleId: "R-PAY-002",
    domainArea: "שכר ותגמול",
    topic: "אי-התאמה בין מנגנון תגמול למסמכים",
    inputs: ["PAY-03", "PAY-04", "DOC-03", "DOC-05", "cross_check.pay.contract_payslip_mismatch"],
    conditionRaw: "AI מזהה סתירה בין מסמך לתלוש/תיאור",
    automationLevel: "AI",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לבחון הפרשים ותנאי זכאות.",
    possibleService: "בדיקת תכנית תגמול",
    legalSourceUrl: null,
    cautionNote: "לא לקבוע סיווג בונוס/עמלה ללא בדיקה משפטית.",
    // Entirely AI/cross-check dependent — decidable only via the
    // cross-check engine's own contract/payslip comparison fact.
    evaluate: (facts) => factTrue(facts, "cross_check.pay.contract_payslip_mismatch"),
  },

  // ---------------------------------------------------------------
  // סיום העסקה — TERM
  // ---------------------------------------------------------------
  {
    ruleId: "R-TERM-001",
    domainArea: "סיום העסקה",
    topic: "אין זימון שימוע בכתב",
    inputs: ["TERM-01", "TERM-02"],
    conditionRaw: "TERM-01=כן AND TERM-02=לפעמים/לא",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לשפר נוהל שימוע ולבדוק אירועים פתוחים.",
    possibleService: "נוהל שימוע",
    legalSourceUrl: null,
    cautionNote: "היעדר כתב הוא אינדיקציה חזקה אך יש לבחון ההליך כולו.",
    evaluate: (facts) => answerIn(facts, "TERM-01", ["כן"]) && answerIn(facts, "TERM-02", ["לפעמים", "לא"]),
  },
  {
    ruleId: "R-TERM-002",
    domainArea: "סיום העסקה",
    topic: "זימון ללא נימוקים",
    inputs: ["TERM-03"],
    conditionRaw: "TERM-03=לפעמים/לא",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לעדכן תבניות זימון ולהבטיח פירוט מספק.",
    possibleService: "ליווי שימועים",
    legalSourceUrl: null,
    cautionNote: "יש לבחון את רמת הפירוט בפועל.",
    evaluate: (facts) => answerIn(facts, "TERM-03", ["לפעמים", "לא"]),
  },
  {
    ruleId: "R-TERM-003",
    domainArea: "סיום העסקה",
    topic: "אין תיעוד שימוע",
    inputs: ["TERM-04"],
    conditionRaw: "TERM-04=לפעמים/לא",
    automationLevel: "אוטומטי",
    baseSeverity: 2,
    criticalOverride: false,
    recommendation: "ליצור מנגנון פרוטוקול/תיעוד.",
    possibleService: "נוהל שימוע",
    legalSourceUrl: null,
    cautionNote: "לא כל העדר פרוטוקול כשלעצמו מבטל הליך, אך הוא יוצר סיכון ראייתי.",
    evaluate: (facts) => answerIn(facts, "TERM-04", ["לפעמים", "לא"]),
  },
  {
    ruleId: "R-TERM-004",
    domainArea: "סיום העסקה",
    topic: "החלטה מתקבלת לפני השימוע",
    inputs: ["TERM-05"],
    conditionRaw: "TERM-05=לפני השימוע",
    automationLevel: "אוטומטי",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "עצירת הפרקטיקה ובדיקת תבניות ותהליכים מיידית.",
    possibleService: "ליווי שימועים",
    legalSourceUrl: null,
    cautionNote: "Override קריטי בשל פגיעה אפשרית בליבת זכות הטיעון.",
    evaluate: (facts) => answerIn(facts, "TERM-05", ["לפני השימוע"]),
  },
  {
    ruleId: "R-TERM-005",
    domainArea: "סיום העסקה",
    topic: "כוונת סיום + נסיבה מוגנת",
    inputs: ["TERM-06", "TERM-07"],
    conditionRaw: "TERM-06=כן AND TERM-07=כן/לא יודעת",
    automationLevel: "אוטומטי+Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "אין לבצע שינוי לפני בדיקה משפטית פרטנית.",
    possibleService: "ייעוץ לפני פיטורים",
    legalSourceUrl: "https://www.gov.il/he/service/workers-dismissal-due-to-women-employment-law",
    cautionNote: "אין לבקש מידע רפואי מעבר לנדרש.",
    evaluate: (facts) =>
      answerIn(facts, "TERM-06", ["כן"]) && answerIn(facts, "TERM-07", ["כן", "לא יודעת"]),
  },

  // ---------------------------------------------------------------
  // דיני עבודה — HR / LIT
  // ---------------------------------------------------------------
  {
    ruleId: "R-HR-001",
    domainArea: "דיני עבודה",
    topic: "אין אחראי/ת למניעת הטרדה מינית",
    inputs: ["HR-02"],
    conditionRaw: "HR-02=לא/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "למנות אחראי/ת ולהסדיר דרכי פנייה.",
    possibleService: "הסדרת מניעת הטרדה מינית",
    legalSourceUrl: null,
    cautionNote: "יש לבדוק את חובות המעסיק בהתאם לגודל ולנסיבות.",
    evaluate: (facts) => answerIn(facts, "HR-02", ["לא", "לא יודעת"]),
  },
  {
    ruleId: "R-HR-002",
    domainArea: "דיני עבודה",
    topic: "מעל 25 עובדים ללא תקנון מותאם/מפורסם",
    inputs: ["GEN-04", "HR-04"],
    conditionRaw: "GEN-04>25 AND HR-04=לא/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "להכין ולהפיץ תקנון מותאם.",
    possibleService: "תקנון הטרדה מינית",
    legalSourceUrl: "https://main.knesset.gov.il/News/PressReleases/pages/press01.05.18d.aspx",
    cautionNote: "לבדוק גם מינוי אחראי/ת והנגשה.",
    evaluate: (facts) =>
      answerGreaterThan(facts, "GEN-04", 25) && answerIn(facts, "HR-04", ["לא", "לא יודעת"]),
  },
  {
    ruleId: "R-LIT-001",
    domainArea: "דיני עבודה",
    topic: "הליכים קודמים",
    inputs: ["LIT-01", "LIT-02"],
    conditionRaw: "LIT-01=כן",
    automationLevel: "Manual",
    baseSeverity: 1,
    criticalOverride: false,
    recommendation: "לזהות דפוסים חוזרים ולהפיק Lessons Learned.",
    possibleService: "בדיקת הליכים קודמים",
    legalSourceUrl: null,
    cautionNote: "אינו 'הפרה' בפני עצמו ולא אמור להעלות חומרה מהותית לבדו.",
    // Manual-tagged in the CSV itself — never auto-matched regardless of
    // the condition's own simplicity (OPEN_QUESTIONS.md item 21).
    alwaysRequiresManualReview: true,
    evaluate: () => false,
  },

  // ---------------------------------------------------------------
  // פרטיות — PRIV / CAM / BIO / MON / EMAIL / OFF / RET / INC / DPO
  // ---------------------------------------------------------------
  {
    ruleId: "R-PRIV-001",
    domainArea: "פרטיות",
    topic: "אין/חסר יידוע עובדים",
    inputs: ["PRIV-03", "DOC-07", "document_extraction.privacy_notice.components_incomplete"],
    conditionRaw: "PRIV-03=לא/חלקי OR מסמך חסר רכיבי יידוע",
    automationLevel: "AI+Rule",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "להכין/לעדכן הודעת פרטיות לעובדים.",
    possibleService: "Employee Privacy Notice",
    legalSourceUrl: "https://www.gov.il/he/pages/tikun13_qa?chapterIndex=6",
    cautionNote: "יש להתאים את היידוע לסוגי המידע, מטרות והעברות בפועל.",
    // Second OR clause decidable once the cross-check engine (task #47)
    // produces `document_extraction.privacy_notice.components_incomplete`
    // from a DOC-07 extraction.
    evaluate: (facts) =>
      answerIn(facts, "PRIV-03", ["לא", "באופן חלקי"]) ||
      factTrue(facts, "document_extraction.privacy_notice.components_incomplete"),
  },
  {
    ruleId: "R-PRIV-002",
    domainArea: "פרטיות",
    topic: "גישה רחבה למידע עובדים",
    inputs: ["PRIV-04"],
    conditionRaw: "גישה כוללת מנהלים/עובדים ללא צורך תפקידי ברור",
    automationLevel: "Manual",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לבנות Role-Based Access ולצמצם הרשאות.",
    possibleService: "מיפוי הרשאות",
    legalSourceUrl: null,
    cautionNote: "אין לקבוע עודפות רק מתפקיד כללי; נדרש להבין צורך תפקידי.",
    // "ללא צורך תפקידי ברור" ("without clear role-based need") defines
    // no threshold over PRIV-04's access-holder list — genuinely
    // undecidable, and Manual-tagged besides.
    alwaysRequiresManualReview: true,
    evaluate: () => false,
  },
  {
    ruleId: "R-PRIV-003",
    domainArea: "פרטיות",
    topic: "חשבונות משתמש משותפים",
    inputs: ["PRIV-05"],
    conditionRaw: "PRIV-05=כן",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לבטל חשבונות משותפים ולנהל זיהוי והרשאות אישיות.",
    possibleService: "אבטחת מידע והרשאות",
    legalSourceUrl: null,
    cautionNote: "יש לבחון את רמת האבטחה והמערכות הרלוונטיות.",
    evaluate: (facts) => answerIn(facts, "PRIV-05", ["כן"]),
  },
  {
    ruleId: "R-PRIV-004",
    domainArea: "פרטיות",
    topic: "ספקים עם גישה ללא הסדרה",
    inputs: ["PRIV-06", "PRIV-07"],
    conditionRaw: "PRIV-06≠אין AND PRIV-07=חלקם/לא/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "להסדיר התקשרויות פרטיות ואבטחת מידע.",
    possibleService: "נספחי פרטיות/עיבוד",
    legalSourceUrl: null,
    cautionNote: "יש לזהות תפקיד משפטי של כל ספק והוראות התקנות.",
    evaluate: (facts) =>
      answerExcludesAll(facts, "PRIV-06", ["אין"]) &&
      answerIn(facts, "PRIV-07", ["עם חלקם", "לא", "לא יודעת"]),
  },
  {
    ruleId: "R-CAM-001",
    domainArea: "פרטיות",
    topic: "מצלמה בחדר הלבשה",
    inputs: ["PRIV-09"],
    conditionRaw: "PRIV-09 כולל חדר הלבשה",
    automationLevel: "אוטומטי+Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "בדיקה מיידית של עצם הצילום והפסקת חשיפה עד בירור.",
    possibleService: "בדיקת מצלמות",
    legalSourceUrl: "https://www.gov.il/blobfolder/policy/workplace_camera/he/3-17_0.pdf",
    cautionNote: "דגל חריף; לא לקבוע מסקנה סופית ללא נסיבות, אך יש לתעדף מיידית.",
    evaluate: (facts) => answerIncludesAny(facts, "PRIV-09", ["חדר הלבשה"]),
  },
  {
    ruleId: "R-CAM-002",
    domainArea: "פרטיות",
    topic: "מצלמות ללא יידוע",
    inputs: ["PRIV-08", "PRIV-11"],
    conditionRaw: "PRIV-08=כן AND PRIV-11=לא/חלקי",
    automationLevel: "אוטומטי",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "להסדיר שקיפות, מטרה ומידתיות.",
    possibleService: "בדיקת מצלמות",
    legalSourceUrl: "https://www.gov.il/blobfolder/policy/workplace_camera/he/3-17_0.pdf",
    cautionNote: "הנחיית הרשות מדגישה שקיפות ומידתיות ביחסי עבודה.",
    evaluate: (facts) => answerIn(facts, "PRIV-08", ["כן"]) && answerIn(facts, "PRIV-11", ["לא", "חלקית"]),
  },
  {
    ruleId: "R-CAM-003",
    domainArea: "פרטיות",
    topic: "מצלמות ללא שילוט",
    inputs: ["PRIV-12"],
    conditionRaw: "PRIV-12=לא/חלק",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "להשלים שילוט כחלק ממכלול השקיפות.",
    possibleService: "בדיקת מצלמות",
    legalSourceUrl: "https://www.gov.il/blobfolder/policy/workplace_camera/he/3-17_0.pdf",
    cautionNote: "השילוט אינו מחליף יידוע עובדים.",
    evaluate: (facts) => answerIn(facts, "PRIV-12", ["לא", "בחלק מהאזורים"]),
  },
  {
    ruleId: "R-CAM-004",
    domainArea: "פרטיות",
    topic: "הקלטת קול במצלמות",
    inputs: ["PRIV-13"],
    conditionRaw: "PRIV-13=כן/לא יודעת",
    automationLevel: "אוטומטי+Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "בדיקה משפטית נפרדת ומיידית של ההקלטה.",
    possibleService: "בדיקת מצלמות והקלטה",
    legalSourceUrl: "https://www.gov.il/blobfolder/policy/workplace_camera/he/3-17_0.pdf",
    cautionNote: "עשויות להתעורר גם סוגיות לפי דינים נוספים; אין להסתפק בדיני פרטיות.",
    evaluate: (facts) => answerIn(facts, "PRIV-13", ["כן", "לא יודעת"]),
  },
  {
    ruleId: "R-CAM-005",
    domainArea: "פרטיות",
    topic: "שימוש בצילום לפיקוח/משמעת",
    inputs: ["PRIV-10", "PRIV-16"],
    conditionRaw: "PRIV-16=כן/לעיתים",
    automationLevel: "Rule+Manual",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "להשוות בין המטרה שהוגדרה לבין השימוש בפועל.",
    possibleService: "בדיקת מצלמות",
    legalSourceUrl: "https://www.gov.il/blobfolder/policy/workplace_camera/he/3-17_0.pdf",
    cautionNote: "שימוש משני עשוי להיות בעייתי במיוחד אם לא הוגדר מראש.",
    evaluate: (facts) => answerIn(facts, "PRIV-16", ["כן", "לעיתים"]),
  },
  {
    ruleId: "R-CAM-006",
    domainArea: "פרטיות",
    topic: "שמירת צילומים ממושכת/לא ידועה",
    inputs: ["PRIV-15"],
    conditionRaw: "PRIV-15=>90 ימים/ללא מגבלה/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לקבוע תקופת שמירה התואמת למטרה ולצמצם עודף.",
    possibleService: "מדיניות שמירת מידע",
    legalSourceUrl: "https://www.gov.il/blobfolder/policy/workplace_camera/he/3-17_0.pdf",
    cautionNote: "90 יום הוא טריגר לבחינה, לא 'קו חוקי' אוטומטי.",
    evaluate: (facts) =>
      answerIn(facts, "PRIV-15", ["מעל 90 ימים", "ללא מגבלת זמן ידועה", "לא יודעת"]),
  },
  {
    ruleId: "R-BIO-001",
    domainArea: "פרטיות",
    topic: "ביומטריה ללא חלופה",
    inputs: ["PRIV-17", "PRIV-18", "TIME-02"],
    conditionRaw: "PRIV-17=כן AND PRIV-18=לא/לא יודעת",
    automationLevel: "אוטומטי+Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "לבחון נחיצות, חלופה פחות פוגענית, יידוע והסדרה.",
    possibleService: "בדיקת ביומטריה",
    legalSourceUrl: "https://www.gov.il/BlobFolder/policy/biometric_workplace/he/BiometriWorkplace.pdf",
    cautionNote: "עמדת הרשות מ-2026 מחייבת בחינת מידתיות וחלופות.",
    evaluate: (facts) => answerIn(facts, "PRIV-17", ["כן"]) && answerIn(facts, "PRIV-18", ["לא", "לא יודעת"]),
  },
  {
    ruleId: "R-MON-001",
    domainArea: "פרטיות",
    topic: "ניטור דיגיטלי ללא יידוע",
    inputs: ["PRIV-19", "PRIV-21"],
    conditionRaw: "PRIV-19≠אין AND PRIV-21=לא/חלקי",
    automationLevel: "אוטומטי",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "להסדיר שקיפות, תכלית והיקף לפני המשך השימוש.",
    possibleService: "מדיניות ניטור עובדים",
    legalSourceUrl: "https://mojforms.justice.gov.il/mojaemprivacyprotectionauthority/dpiaform.html",
    cautionNote: "נדרש לבחון כל אמצעי ניטור בנפרד.",
    evaluate: (facts) =>
      answerExcludesAll(facts, "PRIV-19", ["אין"]) && answerIn(facts, "PRIV-21", ["לא", "חלקית"]),
  },
  {
    ruleId: "R-MON-002",
    domainArea: "פרטיות",
    topic: "ניטור מחוץ לשעות העבודה",
    inputs: ["PRIV-19", "PRIV-22"],
    conditionRaw: "PRIV-22=כן/תלוי",
    automationLevel: "אוטומטי+Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "לבדוק אפשרות כיבוי/צמצום ונחיצות המעקב מחוץ לעבודה.",
    possibleService: "מדיניות ניטור עובדים",
    legalSourceUrl: "https://mojforms.justice.gov.il/mojaemprivacyprotectionauthority/dpiaform.html",
    cautionNote: "דגל חמור במיוחד בנתוני מיקום ומכשירים אישיים.",
    evaluate: (facts) => answerIn(facts, "PRIV-22", ["כן", "תלוי במערכת"]),
  },
  {
    ruleId: "R-EMAIL-001",
    domainArea: "פרטיות",
    topic: 'גישה לדוא"ל ללא פרוצדורה',
    inputs: ["PRIV-23"],
    conditionRaw: "PRIV-23=לא/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לקבוע נוהל גישה, נסיבות, הרשאות ותיעוד.",
    possibleService: 'מדיניות מערכות ודוא"ל',
    legalSourceUrl: null,
    cautionNote: "נדרשת התאמה לפסיקה ולנסיבות השימוש בתיבה.",
    evaluate: (facts) => answerIn(facts, "PRIV-23", ["לא", "לא יודעת"]),
  },
  {
    ruleId: "R-OFF-001",
    domainArea: "פרטיות",
    topic: "הרשאות אינן מבוטלות בסיום",
    inputs: ["PRIV-24"],
    conditionRaw: "PRIV-24=בתוך מספר ימים/לא באופן קבוע/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לקבוע ביטול הרשאות מיידי ומתועד.",
    possibleService: "נוהל Offboarding",
    legalSourceUrl: null,
    cautionNote: "רמת החומרה עולה אם נשמרת גישה למידע רגיש.",
    evaluate: (facts) =>
      answerIn(facts, "PRIV-24", ["בתוך מספר ימים", "לא באופן קבוע", "לא יודעת"]),
  },
  {
    ruleId: "R-OFF-002",
    domainArea: "פרטיות",
    topic: 'העברת תיבת דוא"ל למנהל',
    inputs: ["PRIV-25"],
    conditionRaw: "PRIV-25=מועברת למנהל/נשארת פעילה",
    automationLevel: "Rule+Manual",
    baseSeverity: 4,
    criticalOverride: false,
    recommendation: "לבדוק מידתיות, תקופת מעבר, יידוע וגישה לתוכן.",
    possibleService: "מדיניות סיום עבודה ופרטיות",
    legalSourceUrl: null,
    cautionNote: "העברה אוטומטית לכל התוכן אינה מומלצת ללא בדיקה.",
    evaluate: (facts) => answerIn(facts, "PRIV-25", ["מועברת למנהל", "נשארת פעילה"]),
  },
  {
    ruleId: "R-RET-001",
    domainArea: "פרטיות",
    topic: "אין מדיניות שמירת מידע",
    inputs: ["PRIV-26"],
    conditionRaw: "PRIV-26=לא/לא יודעת",
    automationLevel: "אוטומטי",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לבנות מטריצת שמירה ומחיקה לפי קטגוריה וצורך.",
    possibleService: "מדיניות שמירת מידע",
    legalSourceUrl: null,
    cautionNote: "אין לקבוע תקופות אחידות לכל סוגי המידע.",
    evaluate: (facts) => answerIn(facts, "PRIV-26", ["לא", "לא יודעת"]),
  },
  {
    ruleId: "R-INC-001",
    domainArea: "פרטיות",
    topic: "אירוע אבטחת מידע בעבר",
    inputs: ["PRIV-27"],
    conditionRaw: "PRIV-27=כן",
    automationLevel: "Manual",
    baseSeverity: 5,
    criticalOverride: true,
    recommendation: "לבדוק חובות תיעוד/דיווח והפקת לקחים.",
    possibleService: "טיפול באירוע פרטיות",
    legalSourceUrl: null,
    cautionNote: "יש לצמצם איסוף פרטי האירוע בשאלון ולהעביר לבדיקה מאובטחת.",
    // Manual-tagged in the CSV itself — a past security incident is
    // always routed to direct attorney review, never auto-matched.
    alwaysRequiresManualReview: true,
    evaluate: () => false,
  },
  {
    ruleId: "R-DPO-001",
    domainArea: "פרטיות",
    topic: "Screening לחובת DPO",
    inputs: ["PRIV-28"],
    conditionRaw: "PRIV-28=לא/לא יודעת AND קיימים מאפייני פעילות החייבים בדיקה",
    automationLevel: "Rule+Manual",
    baseSeverity: 3,
    criticalOverride: false,
    recommendation: "לבצע Screening ייעודי לפי סעיף 17ב1 וגילוי דעת 2026.",
    possibleService: "בחינת חובת DPO",
    legalSourceUrl: "https://www.gov.il/he/pages/amendment-13-26-07-26",
    cautionNote: "אין להסיק חובה רק ממידע עובדים; זהו Screening ארגוני.",
    // Second clause ("activity characteristics requiring review exist")
    // defines no criteria anywhere in the source CSVs — genuinely
    // undecidable, never auto-matched.
    alwaysRequiresManualReview: true,
    evaluate: () => false,
  },
] as const;

/** For O(1) lookup by Rule ID — used by validateCatalog.ts and the findings/report layers. */
export const RULE_CATALOG_BY_ID: ReadonlyMap<string, RuleDefinition> = new Map(
  RULE_CATALOG.map((rule) => [rule.ruleId, rule]),
);
